fos_rest:
  view:
    view_response_listener:  true
  routing_loader:
    default_format: json
  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
      - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
  exception:
    enabled: true
    exception_controller: 'fos_rest.exception.controller:showAction'
    codes:
      Doctrine\ODM\MongoDB\DocumentNotFoundException: 404
      Exception: 400
